- name: copy pyenv-installer script
  copy:
    src: pyenv-installer
    dest: /home/ubuntu/pyenv-installer
    mode: 0744
    owner: ubuntu
    group: ubuntu

- name: add pyenv to path
  ansible.builtin.blockinfile:
    path: /home/ubuntu/.bash_profile
    create: true
    mode: 0644
    owner: ubuntu
    group: ubuntu
    block: |
      export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

- name: run pyenv-installer if no pyenv
  become: no
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: if [ ! -d /home/ubuntu/.pyenv ]; then /usr/bin/bash /home/ubuntu/pyenv-installer; fi
    creates: /home/ubuntu/.pyenv

- name: install Python 3.8.18
  become: no
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: . /home/ubuntu/.bash_profile && pyenv install 3.8.18
    creates: /home/ubuntu/.pyenv/versions/3.8.18

- name: install Python 3.12.2
  become: no
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: . /home/ubuntu/.bash_profile && pyenv install 3.12.2
    creates: /home/ubuntu/.pyenv/versions/3.12.2
